WebsiteBanHang/Controllers/QuanLySachController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteBanHang.Models;
using PagedList;
using PagedList.Mvc;

namespace WebsiteBanHang.Controllers
{
    public class QuanLySachController : Controller
    {
        // GET: QuanLySach
        Data_Entities db = new Data_Entities();
        public ActionResult Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;
            return View(db.SACH.ToList().OrderBy(n => n.Ten_Sach).ToPagedList(pageNumber, pageSize));
        }
        //Thêm mới
        [HttpGet]
        public ActionResult ThemMoi()
        {
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.CHUDE.ToList().OrderBy(n => n.Ten_ChuDe), "Ma_ChuDe", "Ten_ChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.Ten_NXB), "Ma_NXB", "Ten_NXB");
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ThemMoi(SACH sach, HttpPostedFileBase fileUpload)
        {
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.CHUDE.ToList().OrderBy(n => n.Ten_ChuDe), "Ma_ChuDe", "Ten_ChuDe");
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.Ten_NXB), "Ma_NXB", "Ten_NXB");
            //Kiểm tra đường dẫn ảnh bìa
            if (fileUpload == null)
            {
                ViewBag.ThongBao = "Chọn hình ảnh";
                return View();
            }
            //Thêm vào CSDL
            if (ModelState.IsValid)
            {
                //Lưu tên file
                var fileName = Path.GetFileName(fileUpload.FileName);
                //Lưu đường dẫn của file
                var path = Path.Combine(Server.MapPath("~/Content/img/AnhBia"), fileName);
                //Kiểm tra hình ảnh đã tồn tại chưa
                if (System.IO.File.Exists(path))
                {
                    ViewBag.ThongBao = "Hình ảnh đã tồn tại";
                }
                else
                {
                    fileUpload.SaveAs(path);
                }
                sach.AnhBia = fileUpload.FileName;
                db.SACH.Add(sach);
                db.SaveChanges();
            }
            return View();
        }
        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(string MaSach)
        {
            //Lấy ra đối tượng sách theo mã
            SACH sach = db.SACH.SingleOrDefault(n => n.Ma_Sach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.CHUDE.ToList().OrderBy(n => n.Ten_ChuDe), "Ma_ChuDe", "Ten_ChuDe", sach.Ma_ChuDe);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.Ten_NXB), "Ma_NXB", "Ten_NXB", sach.Ma_NXB);
            return View(sach);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ChinhSua(SACH sach)
        {
            //Thêm vào CSDL
            if (ModelState.IsValid)
            {
                //Thực hiện cập nhật trong model
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            //Đưa dữ liệu vào dropdownlist
            ViewBag.MaChuDe = new SelectList(db.CHUDE.ToList().OrderBy(n => n.Ten_ChuDe), "Ma_ChuDe", "Ten_ChuDe", sach.Ma_ChuDe);
            ViewBag.MaNXB = new SelectList(db.NHAXUATBAN.ToList().OrderBy(n => n.Ten_NXB), "Ma_NXB", "Ten_NXB", sach.Ma_NXB);
            return RedirectToAction("Index");
        }
        //Xem chi tiết sách
        public ActionResult XemChiTiet(string MaSach)
        {

            //Lấy ra đối tượng sách theo mã
            SACH sach = db.SACH.SingleOrDefault(n => n.Ma_Sach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        //Xóa sách
        [HttpGet]
        public ActionResult Xoa(string MaSach)
        {
            //Lấy ra đối tượng sách theo mã
            SACH sach = db.SACH.SingleOrDefault(n => n.Ma_Sach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sach);
        }
        [HttpPost, ActionName("Xoa")]
        public ActionResult XacNhanXoa(string MaSach)
        {
            SACH sach = db.SACH.SingleOrDefault(n => n.Ma_Sach == MaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            db.SACH.Remove(sach);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

WebsiteBanHang/Views/QuanLySach/ChinhSua.cshtml
@model WebsiteBanHang.Models.SACH
@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Chỉnh sửa</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Ten_Sach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_Sach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_Sach, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Gia_Ban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia_Ban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia_Ban, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhBia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhBia, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_CapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Ngay_CapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_CapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong_Ton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong_Ton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong_Ton, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ma_NXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB");
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ma_ChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe");
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">@Model.MoTa</textarea>
            </div>
        </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

WebsiteBanHang/Views/QuanLySach/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model PagedList.PagedList<WebsiteBanHang.Models.SACH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Trang chủ</h2>

<p>
    @Html.ActionLink("Thêm mới", "ThemMoi")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.First().Ma_Sach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Ten_Sach)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Gia_Ban)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().MoTa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().AnhBia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().Ngay_CapNhat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().SoLuong_Ton)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().NHAXUATBAN.Ten_NXB)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.First().CHUDE.Ten_ChuDe)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ma_Sach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_Sach)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gia_Ban)
            </td>
            <td>
                @Html.Raw(item.MoTa)
            </td>
            <td>
                <div id="AnhBia"><img src="@Url.Content("~/Content/img/AnhBia/" + item.AnhBia)" width="100" height="150" /></div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ngay_CapNhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong_Ton)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NHAXUATBAN.Ten_NXB)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CHUDE.Ten_ChuDe)
            </td>
            <td>
                @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach = item.Ma_Sach }) |
                @Html.ActionLink("Xem chi tiết", "XemChiTiet", new { @MaSach = item.Ma_Sach }) |
                @Html.ActionLink("Xóa", "Xoa", new { @MaSach = item.Ma_Sach })
            </td>
        </tr>
    }

</table>
@*Tạo link liên kết các trang*@
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .MenuTrang li {
        display: inline;
    }
</style>

WebsiteBanHang/Views/QuanLySach/ThemMoi.cshtml
@model WebsiteBanHang.Models.SACH
@{
    ViewBag.Title = "ThemMoi";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Thêm mới</h2>

@*Thêm thuộc tính cho form để upload ảnh*@
@using (Html.BeginForm("ThemMoi", "QuanLySach", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sach</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Ten_Sach, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ten_Sach, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ten_Sach, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Gia_Ban, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia_Ban, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia_Ban, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*Name của thẻ input file phải trùng tên với tham số bên controller*@
                <input type="file" name="fileUpload" />
                @*Thông báo trùng*@
                @ViewBag.ThongBao
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ngay_CapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ngay_CapNhat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ngay_CapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.SoLuong_Ton, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoLuong_Ton, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoLuong_Ton, "", new { @class = "text-danger" })
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ma_NXB, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNXB")
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.Ma_ChuDe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaChuDe")
            </div>
        </div>

        <br />

        <div class="form-group">
            @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <textarea name="MoTa">Easy! You should check out MoxieManager!</textarea>
            </div>
        </div>

        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Trở về", "Index")
</div>

WebsiteBanHang/Views/QuanLySach/XemChiTiet.cshtml
@model WebsiteBanHang.Models.SACH
@{
    ViewBag.Title = "XemChiTiet";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h2>Xem chi tiết</h2>

<div>
    <h4>Sách</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ma_Sach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ma_Sach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_Sach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_Sach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia_Ban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia_Ban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_CapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_CapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong_Ton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong_Ton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHAXUATBAN.Ten_NXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHAXUATBAN.Ten_NXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CHUDE.Ten_ChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUDE.Ten_ChuDe)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Chỉnh sửa", "ChinhSua", new { @MaSach = Model.Ma_Sach }) |
    @Html.ActionLink("Trở về", "Index")
</p>

WebsiteBanHang/Views/QuanLySach/Xoa.cshtml
@model WebsiteBanHang.Models.SACH
@{
    ViewBag.Title = "Xoa";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<h3>Bạn có chắc muốn xóa quyển sách này không</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ma_Sach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ma_Sach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_Sach)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_Sach)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia_Ban)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia_Ban)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhBia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhBia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ngay_CapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ngay_CapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong_Ton)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong_Ton)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NHAXUATBAN.Ten_NXB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NHAXUATBAN.Ten_NXB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CHUDE.Ten_ChuDe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CHUDE.Ten_ChuDe)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" /> |
            @Html.ActionLink("Trở về", "Index")
        </div>
    }
</div>